# Generated by Django 3.2.25 on 2024-08-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='taught_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjects',
            name='with_lessons',
            field=models.ManyToManyField(blank=True, to='Works.Lessons'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='taught_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classes',
            name='Enroll',
            field=models.ManyToManyField(blank=True, related_name='enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classes',
            name='with_subjects',
            field=models.ManyToManyField(blank=True, to='Works.Subjects'),
        ),
    ]
