# Generated by Django 5.1.1 on 2024-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0004_classes_language_classes_paid_users_classes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_hiden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classes',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessons',
            name='is_hiden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessons',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
