# Generated by Django 5.1.1 on 2025-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_is_content_moderation_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='major',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
