# Generated by Django 5.1.1 on 2024-12-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_hiden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
