# Generated by Django 5.1.1 on 2025-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_is_hiden_blogpost_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(max_length=200),
        ),
    ]
