# Generated by Django 3.2.25 on 2024-08-15 19:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('video', 'Video'), ('Audeo', 'Audeo')], max_length=10)),
                ('display_image', models.FileField(blank=True, upload_to='content/')),
                ('video', models.FileField(blank=True, upload_to='content/')),
                ('Audeo', models.FileField(blank=True, upload_to='content/')),
                ('paper_file', models.FileField(blank=True, upload_to='content/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('display_image', models.ImageField(null=True, upload_to='display_images/')),
                ('date_updated', models.DateField(auto_now=True)),
                ('ISBN', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section_video', models.FileField(blank=True, upload_to='content/')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section_video', models.FileField(blank=True, null=True, upload_to='content/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='my_library.section')),
            ],
        ),
    ]
