# Generated by Django 5.1.1 on 2025-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0005_content_is_hiden_content_reported_ebook_is_hiden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='ISBN',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
