# Generated by Django 3.2.25 on 2024-08-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reciepient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
