# Generated by Django 5.1.1 on 2025-02-12 20:09

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_on', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('unit_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Duration', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('science', 'science'), ('Arts', 'Arts'), ('Engineering', 'Engineering'), ('Business', 'Business'), ('creative_work', 'creative_work'), ('Languages', 'Languages'), ('computor_science', 'computer_science'), ('others', 'others'), ('Religios_studies', 'Religious_studies')], max_length=200)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('is_hiden', models.BooleanField(default=False)),
                ('Enroll', models.ManyToManyField(blank=True, related_name='enrolled', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('with_course_units', models.ManyToManyField(blank=True, to='free.course_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('power', models.CharField(max_length=11)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('notes', models.FileField(upload_to='notes/')),
                ('video', models.FileField(upload_to='video/')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('transcript_file', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('reported', models.BooleanField(default=False)),
                ('is_hiden', models.BooleanField(default=False)),
                ('lesson_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taecher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course_unit',
            name='with_lessons',
            field=models.ManyToManyField(blank=True, to='free.lessons'),
        ),
    ]
