# Generated by Django 5.1.1 on 2025-02-17 19:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('video', 'Video'), ('Audeo', 'Audeo')], max_length=10)),
                ('display_image', models.FileField(blank=True, upload_to='content/')),
                ('video', models.FileField(blank=True, upload_to='content/')),
                ('Audeo', models.FileField(blank=True, upload_to='content/')),
                ('paper_file', models.FileField(blank=True, upload_to='content/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('is_hiden', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('display_image', models.ImageField(null=True, upload_to='display_images/')),
                ('date_updated', models.DateField(auto_now=True)),
                ('ISBN', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('reported', models.BooleanField(default=False)),
                ('is_hiden', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section_video', models.FileField(blank=True, upload_to='content/')),
                ('Freeebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='free.freeebook')),
                ('section_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeSub_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('section_video', models.FileField(blank=True, null=True, upload_to='content/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='free.freesection')),
                ('subsection_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsection_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
