# Generated by Django 3.2.25 on 2024-08-15 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2550)),
                ('Date', models.DateField(auto_now=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examination_name', models.CharField(max_length=2550)),
                ('semester', models.CharField(max_length=2550)),
                ('Date', models.DateField(auto_now=True)),
                ('instructins', ckeditor.fields.RichTextField()),
                ('Duration', models.IntegerField()),
                ('Question', ckeditor.fields.RichTextField()),
                ('release', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_answer_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('scores', models.IntegerField()),
                ('Generalcomment', ckeditor.fields.RichTextField()),
                ('submittedat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterforExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registered_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2550)),
                ('Date', models.DateField(auto_now=True)),
                ('instructins', ckeditor.fields.RichTextField()),
                ('Duration', models.IntegerField()),
                ('Question', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2550)),
                ('Date', models.DateField(auto_now=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test_answer_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('marks', models.IntegerField()),
                ('General_comment', ckeditor.fields.RichTextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
