# Generated by Django 3.2.25 on 2024-08-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Works', '0001_initial'),
        ('Examination', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_answer_response',
            name='response_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_answer_response',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='Answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answere_given_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='Answered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answeredto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_answer',
            name='Subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subjectname', to='Works.subjects'),
        ),
        migrations.AddField(
            model_name='test',
            name='Subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subject_name', to='Works.subjects'),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatd_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerforexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Register', to='Examination.exam'),
        ),
        migrations.AddField(
            model_name='registerforexam',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registerforexam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam_answer_response',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Works.classes'),
        ),
        migrations.AddField(
            model_name='exam_answer_response',
            name='Examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam', to='Examination.exam'),
        ),
        migrations.AddField(
            model_name='exam_answer_response',
            name='responseby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responseby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam_answer_response',
            name='responseto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responseto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='Cours_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cours_name', to='Works.classes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='Answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='Answered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answered_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='Cours_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Coursname', to='Works.classes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='Examination_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examinationname', to='Examination.exam'),
        ),
    ]
