# Generated by Django 5.1.1 on 2024-12-17 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0004_test_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='candidates',
            field=models.ManyToManyField(related_name='exam_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
