# Generated by Django 5.1.1 on 2025-01-06 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0005_exam_candidates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='exam_registered', to=settings.AUTH_USER_MODEL),
        ),
    ]
