# Generated by Django 5.1.1 on 2025-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0006_alter_exam_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Examination_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exam_answer_response',
            name='semester',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test',
            name='semester',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_answer',
            name='semester',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='test_answer_response',
            name='semester',
            field=models.CharField(max_length=200),
        ),
    ]
